#!/usr/bin/env node
/**
 * refresh.mjs — pull fresh dispatches into the Miasma Coding Agent Arena.
 *
 * Zero dependencies. Uses Node's built-in fetch (Node 18+).
 * For every agent that has a `repo`, it fetches the GitHub releases Atom feed
 * and merges new releases into the curated seed, then rewrites:
 *    - news.json   (canonical data store)
 *    - data.js     (browser wrapper: window.NEWS = <json>)
 *
 * Curated seed items are always kept; live releases are added on top, deduped,
 * newest first, capped per agent. If a feed fails, that agent is left untouched.
 *
 *   $ node refresh.mjs
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DIR = dirname(fileURLToPath(import.meta.url));
const JSON_PATH = join(DIR, "news.json");
const DATA_PATH = join(DIR, "data.js");

const RELEASES_PER_REPO = 5; // how many latest releases to consider
const PER_AGENT_CAP = 9;     // max items kept per agent after merge
const SUMMARY_LEN = 220;

// ---------- load canonical store ----------
async function loadStore() {
  try {
    return JSON.parse(await readFile(JSON_PATH, "utf8"));
  } catch (e) {
    console.error("✗ could not read news.json:", e.message);
    console.error("  Run from the project directory; news.json must exist as the seed.");
    process.exit(1);
  }
}

// ---------- minimal Atom parser (no deps) ----------
function pick(block, tag) {
  const m = block.match(new RegExp("<" + tag + "[^>]*>([\\s\\S]*?)</" + tag + ">", "i"));
  return m ? m[1] : "";
}
function decode(s) {
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
function parseAtom(xml) {
  const entries = [];
  const re = /<entry>([\s\S]*?)<\/entry>/g;
  let m;
  while ((m = re.exec(xml)) && entries.length < RELEASES_PER_REPO) {
    const block = m[1];
    const linkMatch = block.match(/<link[^>]*href="([^"]+)"/i);
    entries.push({
      title: decode(pick(block, "title")) || "Release",
      url: linkMatch ? linkMatch[1] : "",
      updated: (pick(block, "updated") || pick(block, "published")).trim(),
      content: decode(pick(block, "content"))
    });
  }
  return entries;
}

function toItem(entry) {
  let summary = entry.content || "New release published.";
  if (summary.length > SUMMARY_LEN) summary = summary.slice(0, SUMMARY_LEN - 1).trimEnd() + "…";
  return {
    date: (entry.updated || "").slice(0, 10) || new Date().toISOString().slice(0, 10),
    tag: "release",
    title: entry.title,
    summary,
    url: entry.url,
    source: "github.com"
  };
}

async function fetchReleases(repo) {
  const url = `https://github.com/${repo}/releases.atom`;
  const res = await fetch(url, { headers: { "User-Agent": "miasma-arena-refresh" } });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return parseAtom(await res.text()).map(toItem);
}

// ---------- merge ----------
const norm = (s) => (s || "").toLowerCase().replace(/[^a-z0-9]+/g, "").slice(0, 60);

function mergeItems(seed, live) {
  const seen = new Set();
  const out = [];
  for (const it of [...live, ...seed]) {
    const key = norm(it.url) || norm(it.title);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(it);
  }
  out.sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  return out.slice(0, PER_AGENT_CAP);
}

// ---------- write ----------
async function writeOutputs(store) {
  const json = JSON.stringify(store, null, 2);
  await writeFile(JSON_PATH, json + "\n", "utf8");
  const banner =
    "/* AUTO-GENERATED by refresh.mjs — edits here are overwritten.\n" +
    "   Canonical data lives in news.json. */\n";
  const wrapper =
    banner +
    "window.NEWS = " + json + ";\n" +
    'if (typeof module !== "undefined" && module.exports) { module.exports = window.NEWS; }\n';
  await writeFile(DATA_PATH, wrapper, "utf8");
}

// ---------- main ----------
async function main() {
  const store = await loadStore();
  const agents = store.agents || {};
  let added = 0, touched = 0;

  for (const key of Object.keys(agents)) {
    const a = agents[key];
    if (!a.repo) {
      console.log(`· ${a.name.padEnd(10)} no repo feed — keeping ${a.items.length} curated`);
      continue;
    }
    try {
      const live = await fetchReleases(a.repo);
      const before = a.items.length;
      a.items = mergeItems(a.items, live);
      const delta = a.items.length - before;
      added += Math.max(0, delta);
      touched++;
      console.log(`✓ ${a.name.padEnd(10)} ${a.repo} → ${live.length} live, ${a.items.length} total (${delta >= 0 ? "+" : ""}${delta})`);
    } catch (e) {
      console.log(`✗ ${a.name.padEnd(10)} ${a.repo} feed failed (${e.message}) — keeping seed`);
    }
  }

  store.generatedAt = new Date().toISOString();
  store.source = touched ? "live+seed" : "seed";
  await writeOutputs(store);
  console.log(`\nWrote news.json + data.js · ${touched} feeds refreshed · ${added} new item(s) · ${store.generatedAt}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
